title: "Your Name's Portfolio"
description: "Data Scientist | Machine Learning | AI"
author: "Your Name"
github_username: your-username
linkedin: "your-linkedin-profile"
email: "your-email@example.com"
theme: minima  # Change if using a different theme
